version: '3'

services:
    db:
        image: postgres:alpine
        restart: always
        expose:
            - 5432
        volumes:
            - "./init/postgres:/docker-entrypoint-initdb.d"
            - "./data/postgres_data:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: blog
    python:
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - .:/Blog
        ports:
            - 8000:8000
